# Aufgabe 1

In [3]:
import pandas as pd

population = pd.read_csv(
    "countries_population.csv",
    sep=" ", 
    thousands=",",
    quotechar="'", 
    index_col=0, 
    names=["Country", "Population"])
population.head()

                Population
Country
China           1355692576
India           1236344631
European Union   511434812
United States    318892103
Indonesia        253609643

# Aufgabe 2

## Population & Density

In [8]:
states = pd.read_csv("bundeslaender.txt", sep=" ")
# states = states[["land", "area", "female", "male"]]

states["population"] = states["male"] + states["female"]

states["density"] = ((states["population"] * 1000) / states["area"]).round()

states.to_csv("density.txt", sep=" ")

states

                      land      area  male  female  population  density
0        Baden-Württemberg  35751.65  5271    5465       10736    300.0
1                   Bayern  70551.57  6103    6366       12469    177.0
2                   Berlin    891.85  1660    1736        3396   3808.0
3              Brandenburg  29478.61  1267    1293        2560     87.0
4                   Bremen    404.28   321     342         663   1640.0
5                  Hamburg    755.16   849     894        1743   2308.0
6                   Hessen  21114.79  2983    3109        6092    289.0
7   Mecklenburg-Vorpommern  23180.14   846     861        1707     74.0
8            Niedersachsen  47624.20  3918    4076        7994    168.0
9      Nordrhein-Westfalen  34085.29  8797    9261       18058    530.0
10         Rheinland-Pfalz  19853.36  1990    2069        4059    204.0
11                Saarland   2568.70   510     540        1050    409.0
12                 Sachsen  18415.51  2083    2191        4274    232.0
13          Sachsen-Anhalt  20446.31  1206    1264        2470    121.0
14      Schleswig-Holstein  15799.38  1385    1448        2833    179.0
15               Thüringen  16172.10  1150    1185        2335    144.0

## Mehr Frauen als Männer

In [11]:
states_more_females = states.loc[states["female"] > states["male"]]

print("Anzahl der Bundesländer mit größerer weiblicher Bevölkerung " + str(states_more_females.shape[0]))
states_more_females

Anzahl der Bundesländer mit größerer weiblicher Bevölkerung 16

                      land      area  male  female  population  density
0        Baden-Württemberg  35751.65  5271    5465       10736    300.0
1                   Bayern  70551.57  6103    6366       12469    177.0
2                   Berlin    891.85  1660    1736        3396   3808.0
3              Brandenburg  29478.61  1267    1293        2560     87.0
4                   Bremen    404.28   321     342         663   1640.0
5                  Hamburg    755.16   849     894        1743   2308.0
6                   Hessen  21114.79  2983    3109        6092    289.0
7   Mecklenburg-Vorpommern  23180.14   846     861        1707     74.0
8            Niedersachsen  47624.20  3918    4076        7994    168.0
9      Nordrhein-Westfalen  34085.29  8797    9261       18058    530.0
10         Rheinland-Pfalz  19853.36  1990    2069        4059    204.0
11                Saarland   2568.70   510     540        1050    409.0
12                 Sachsen  18415.51  2083    2191        4274    232.0
13          Sachsen-Anhalt  20446.31  1206    1264        2470    121.0
14      Schleswig-Holstein  15799.38  1385    1448        2833    179.0
15               Thüringen  16172.10  1150    1185        2335    144.0

## > 1000 Einwohner pro km2

In [12]:
states.loc[((states["population"] * 1000) / states["area"]) > 1000]

      land    area  male  female  population  density
2   Berlin  891.85  1660    1736        3396   3808.0
4   Bremen  404.28   321     342         663   1640.0
5  Hamburg  755.16   849     894        1743   2308.0

# Aufgabe 3

## Reguläre Wochentage

In [13]:
index = pd.date_range("2025-12-24", "2026-1-6", freq="B")

print("Es gibt " + str(len(index)) + " normale Wochentage/reguläre Arbeitstage in den Weihnachtsferien 2025/26.")
index

Es gibt 10 normale Wochentage/reguläre Arbeitstage in den Weihnachtsferien 2025/26.

DatetimeIndex(['2025-12-24', '2025-12-25', '2025-12-26', '2025-12-29',
               '2025-12-30', '2025-12-31', '2026-01-01', '2026-01-02',
               '2026-01-05', '2026-01-06'],
              dtype='datetime64[ns]', freq='B')

## Sonntage in 2026

In [18]:
index2 = pd.date_range("2025-12-24", "2027-01-06")
index2 = index2[(index2.day == 1) & (index2.weekday == 6)]

print("Vom 24.12.2025 bis zum 6.01.2027 gibt es " + str(len(index2)) + " Sonntage, die auf den 1. des Monats fallen.")

index2

Vom 24.12.2025 bis zum 6.01.2027 gibt es 3 Sonntage, die auf den 1. des Monats fallen.

DatetimeIndex(['2026-02-01', '2026-03-01', '2026-11-01'], dtype='datetime64[ns]', freq=None)