In [1]:
import pandas as pd

# Aufgabe 1

In [2]:

data = { 
    'country': ['Östereich', 'Deutschland', 'Schweiz'],
    'area': [414.6, 891.85, 87.88],
    'population': [1805681, 3562166, 378884]
}

df = pd.DataFrame(data=data, index=['Wien', 'Berlin', 'Zürich'])

df

            country    area  population
Wien      Östereich  414.60     1805681
Berlin  Deutschland  891.85     3562166
Zürich      Schweiz   87.88      378884

In [16]:
df.stack()

Wien    country         Östereich
        area                414.6
        population        1805681
Berlin  country       Deutschland
        area               891.85
        population        3562166
Zürich  country           Schweiz
        area                87.88
        population         378884
dtype: object

In [3]:
df.sort_index()

            country    area  population
Berlin  Deutschland  891.85     3562166
Wien      Östereich  414.60     1805681
Zürich      Schweiz   87.88      378884

In [4]:
df.sort_index().transpose().sort_index().transpose()

          area      country population
Berlin  891.85  Deutschland    3562166
Wien     414.6    Östereich    1805681
Zürich   87.88      Schweiz     378884

In [5]:
df.sort_index().transpose().sort_index()

                 Berlin       Wien   Zürich
area             891.85      414.6    87.88
country     Deutschland  Östereich  Schweiz
population      3562166    1805681   378884

# Aufgabe 2

In [6]:
data = {
    'Gewicht': [65, 58, 58, 45, 43, 99, 68, 60],
    'Größe': [179, 165, 172, 154, 150, 189, 176, 175]
}

s = pd.DataFrame(data=data, index=['Henry', 'Sarah', 'Elke', 'Lulu', 'Vera', 'Toni', 'Maria', 'Chris'])
s

       Gewicht  Größe
Henry       65    179
Sarah       58    165
Elke        58    172
Lulu        45    154
Vera        43    150
Toni        99    189
Maria       68    176
Chris       60    175

In [7]:
def bmi(column):
    return (column['Gewicht'] / ((column['Größe'] / 100) ** 2))

In [8]:
bmi(s)

Henry    20.286508
Sarah    21.303949
Elke     19.605192
Lulu     18.974532
Vera     19.111111
Toni     27.714790
Maria    21.952479
Chris    19.591837
dtype: float64

In [9]:
s[bmi(s).between(18.5, 25)]

       Gewicht  Größe
Henry       65    179
Sarah       58    165
Elke        58    172
Lulu        45    154
Vera        43    150
Maria       68    176
Chris       60    175

Die Tabelle in der Aufgabe wurde mit einer range von [20 - 25] und nicht der, in der Aufgabe angegebenen [18.5 - 25]

In [10]:
s[bmi(s).between(20, 25)]

       Gewicht  Größe
Henry       65    179
Sarah       58    165
Maria       68    176

In [11]:
s[s.index.str.contains('e')]

       Gewicht  Größe
Henry       65    179
Elke        58    172
Vera        43    150

In [18]:
s.sort_values(by='BMI', ascending=False)

       Gewicht  Größe        BMI
Toni        99    189  27.714790
Maria       68    176  21.952479
Sarah       58    165  21.303949
Henry       65    179  20.286508
Elke        58    172  19.605192
Chris       60    175  19.591837
Vera        43    150  19.111111
Lulu        45    154  18.974532

In [12]:
s['BMI'] = bmi(s)

s

       Gewicht  Größe        BMI
Henry       65    179  20.286508
Sarah       58    165  21.303949
Elke        58    172  19.605192
Lulu        45    154  18.974532
Vera        43    150  19.111111
Toni        99    189  27.714790
Maria       68    176  21.952479
Chris       60    175  19.591837

In [22]:
s[(s.BMI < 20) & s.index.str.contains('e')]

      Gewicht  Größe        BMI
Elke       58    172  19.605192
Vera       43    150  19.111111

In [ ]:
s[s.index.str.contains('e')][bmi(s) < 20]

C:\Users\colin\AppData\Local\Temp\ipykernel_17932\2126866880.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  s[s.index.str.contains('e')][bmi(s) < 20]

      Gewicht  Größe        BMI
Elke       58    172  19.605192
Vera       43    150  19.111111

In [ ]:
t = s[s.index.str.contains('e')]
t

       Gewicht  Größe        BMI
Henry       65    179  20.286508
Elke        58    172  19.605192
Vera        43    150  19.111111

In [15]:
t[bmi(s) < 20]

C:\Users\colin\AppData\Local\Temp\ipykernel_17932\2514453307.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  t[bmi(s) < 20]

      Gewicht  Größe        BMI
Elke       58    172  19.605192
Vera       43    150  19.111111

In [23]:
1 + "1"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [25]:
"1" + str(1)

'11'